from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class EvidenceLink:
    term: str
    dataset: str
    evidence: str
    theoretical_role: str


@dataclass(frozen=True)
class ReliabilityTheorySpec:
    scope: str
    evidence_links: tuple[EvidenceLink, ...]
    remaining_ablations: tuple[str, ...]

    @classmethod
    def current(cls) -> "ReliabilityTheorySpec":
        return cls(
            scope=(
                "safe use of unreliable mechanism evidence under non-interventional industrial time series"
            ),
            evidence_links=(
                EvidenceLink(
                    term="Validation-benefit admission",
                    dataset="SKAB",
                    evidence="0.8343 +/- 0.0341 -> 0.8532 +/- 0.0339",
                    theoretical_role="tests whether candidate graph/LLM evidence earns admission by validation usefulness",
                ),
                EvidenceLink(
                    term="Counterfactual edge consistency",
                    dataset="SKAB",
                    evidence="reverse/lag-shift/random-target perturbations reduce Macro-F1",
                    theoretical_role="tests whether admitted edge direction, lag, and target assignment are decision-relevant",
                ),
                EvidenceLink(
                    term="Low-tail non-degradation",
                    dataset="C-MAPSS",
                    evidence="TailGuardedERE reaches 12/12 non-degradation",
                    theoretical_role="tests whether routing is constrained by worst-subset safety rather than only mean gain",
                ),
                EvidenceLink(
                    term="Mechanism non-decoration",
                    dataset="TEP",
                    evidence="0.9549 +/- 0.0023 full vs 0.7432 +/- 0.0102 no expert/no sequence graph",
                    theoretical_role="tests whether mechanism evidence is used by the decision process, not only explanation text",
                ),
                EvidenceLink(
                    term="Near-ceiling preservation",
                    dataset="Hydraulic",
                    evidence="0.9773 +/- 0.0321 -> 0.9784 +/- 0.0301",
                    theoretical_role="tests whether reliability routing avoids damaging already strong targets",
                ),
            ),
            remaining_ablations=(
                "remove validation-benefit admission",
                "remove low-tail guard",
                "remove counterfactual edge check",
                "remove source/complexity pruning",
                "replace reliability admission with attention or edge gate",
                "admit all LLM edges without reliability filtering",
            ),
        )


def _append_evidence_table(lines: list[str], links: tuple[EvidenceLink, ...]) -> None:
    lines.append("| Term | Dataset | Current evidence | Theory role |")
    lines.append("|---|---|---|---|")
    for link in links:
        lines.append(f"| {link.term} | {link.dataset} | {link.evidence} | {link.theoretical_role} |")


def render_report(spec: ReliabilityTheorySpec) -> str:
    lines: list[str] = []
    lines.append("# Reliability-Certified Evidence Admission Model")
    lines.append("")
    lines.append("## 1. Research Object")
    lines.append("")
    lines.append(
        "The paper studies {scope}. The target is not to recover a true causal graph from observational logs. "
        "The target is to decide which expert, LLM, statistical-lag, residual, or graph-path evidence is safe "
        "enough to correct a strong anchor model.".format(scope=spec.scope)
    )
    lines.append("")
    lines.append("For a validation or deployment window `i`:")
    lines.append("")
    lines.append("```math")
    lines.append("p_0(i) = f_0(x_i),")
    lines.append("p_k(i) = f_k(x_i, r_i, g_i, m_k),  k=1,...,K.")
    lines.append("```")
    lines.append("")
    lines.append(
        "`p_0` is the anchor classifier. `p_k` is a challenger generated by one candidate evidence source, "
        "where `r_i` is temporal residual evidence, `g_i` is run/unit/stage context, and `m_k` is a candidate "
        "mechanism rule, lagged edge, graph path, or LLM weak-class verifier."
    )
    lines.append("")
    lines.append("## 2. Local Usefulness Label and Router Objective")
    lines.append("")
    lines.append("The reliability estimator is supervised by whether a candidate improves the anchor locally:")
    lines.append("")
    lines.append("```math")
    lines.append("z_{i,k} = 1[ l(y_i,p_k(i)) < l(y_i,p_0(i)) - epsilon ].")
    lines.append("```")
    lines.append("")
    lines.append("It estimates:")
    lines.append("")
    lines.append("```math")
    lines.append("q_psi(i,k) = P(z_{i,k}=1 | phi(p_0(i), p_k(i), x_i, g_i, m_k)).")
    lines.append("```")
    lines.append("")
    lines.append("A paper-level training objective can be written as:")
    lines.append("")
    lines.append("```math")
    lines.append("L = L_0 + lambda_c L_c + lambda_{ERE} L_{ERE} + lambda_s L_s,")
    lines.append("L_0 = sum_i CE(y_i,p_0(i)),")
    lines.append("L_c = sum_{i,k in A_R} CE(y_i,p_k(i)),")
    lines.append("L_{ERE} = sum_{i,k in A_R} BCE(z_{i,k}, q_psi(i,k)),")
    lines.append("L_s = sum_{k in A_R} max(0, epsilon_s - Q_alpha(Delta M_{k,g})).")
    lines.append("```")
    lines.append("")
    lines.append(
        "This gives the closed-loop optimization target: train a strong anchor, train candidate challengers, "
        "learn when a challenger beats the anchor locally, and penalize candidates whose gain collapses in "
        "low-tail groups."
    )
    lines.append("")
    lines.append("## 3. Candidate-Level Reliability Certificate")
    lines.append("")
    lines.append("A candidate evidence source must first pass a global certificate:")
    lines.append("")
    lines.append("```math")
    lines.append("R_k = beta_1 Delta M_k")
    lines.append("    + beta_2 Q_alpha(Delta M_{k,g})")
    lines.append("    + beta_3 CF_k")
    lines.append("    + beta_4 I_k")
    lines.append("    + beta_5 T_k")
    lines.append("    - beta_6 C_k.")
    lines.append("```")
    lines.append("")
    lines.append("The admitted set is:")
    lines.append("")
    lines.append("```math")
    lines.append("A_R = {k : R_k >= tau_R, Delta M_k >= eta,")
    lines.append("          Q_alpha(Delta M_{k,g}) >= -epsilon, CF_k >= zeta}.")
    lines.append("```")
    lines.append("")
    lines.append(
        "`Delta M_k` is validation gain over the anchor, `Q_alpha` is low-tail group gain, `CF_k` is "
        "counterfactual sensitivity, `I_k` is invariance evidence, `T_k` is source/role trust, and `C_k` "
        "is candidate complexity. The score can be estimated by a learned calibrator, but the admitted "
        "features are externally validated evidence terms rather than hidden model importance values."
    )
    lines.append("")
    lines.append("The deployed predictor is:")
    lines.append("")
    lines.append("```math")
    lines.append("k^*(i) = argmax_{k in A_R} q_psi(i,k),")
    lines.append("p^*(i) = (1-rho_i)p_0(i) + rho_i p_{k^*(i)}(i)")
    lines.append("         if max_{k in A_R} q_psi(i,k) >= tau_q,")
    lines.append("p^*(i) = p_0(i) otherwise.")
    lines.append("```")
    lines.append("")
    lines.append("## 4. Why This Is Not Attention, Edge Gating, or Plain Pruning")
    lines.append("")
    lines.append(
        "The reliability score is not an attention weight: attention redistributes representation mass inside "
        "a network, while `R_k` decides whether an external candidate is allowed to affect the deployed "
        "prediction after validation, low-tail, and counterfactual checks."
    )
    lines.append("")
    lines.append(
        "It is not an edge gate: an edge gate can keep a high-weight relation because it improves the training "
        "loss, but reliability admission can reject that same relation if it fails group safety or "
        "counterfactual perturbation."
    )
    lines.append("")
    lines.append(
        "It is not graph pruning alone: graph pruning changes the graph topology, whereas reliability "
        "admission also decides whether the pruned candidate may correct the anchor on a specific sample. "
        "Pruning is one evidence term inside the certificate, not the whole method."
    )
    lines.append("")
    lines.append("## 5. Why It Prevents Harmful LLM Edges")
    lines.append("")
    lines.append(
        "The framework prevents harmful LLM edges by separating proposal from admission. The LLM may propose "
        "variables, signs, lags, propagation orders, and weak-class rules, but a proposed edge cannot change "
        "the prediction unless it improves validation utility, passes low-tail non-degradation, remains "
        "decision-relevant under counterfactual perturbation, and stays within source/complexity limits. "
        "If those checks fail, deployment falls back to the anchor `p_0` or to the safest validated fallback."
    )
    lines.append("")
    lines.append("## 6. What Counterfactual Perturbation Verifies")
    lines.append("")
    lines.append(
        "Counterfactual perturbation verifies decision relevance, not true physical causality. Reversing an "
        "edge, shifting its lag, or replacing its target asks whether the model's performance depends on the "
        "claimed mechanism structure. A performance drop supports that the edge is used as discriminative "
        "evidence; it still does not prove that the observational log identifies the true causal effect."
    )
    lines.append("")
    lines.append("## 7. Proposition-Level Safety Statement")
    lines.append("")
    lines.append(
        "On the validation protocol, if every deployed candidate satisfies `Q_alpha(Delta M_{k,g}) >= -epsilon` "
        "and the router falls back to `p_0` when `q_psi < tau_q`, then admitted evidence has an empirical "
        "low-tail degradation bound of `epsilon` on the audited groups. This is a protocol certificate, not "
        "a distribution-free causal guarantee."
    )
    lines.append("")
    lines.append("## 8. Evidence Map")
    lines.append("")
    _append_evidence_table(lines, spec.evidence_links)
    lines.append("")
    lines.append("## 9. Remaining Theory-Critical Ablations")
    lines.append("")
    for item in spec.remaining_ablations:
        lines.append(f"- {item}")
    lines.append("")
    lines.append("## 10. Paper-Ready Claim")
    lines.append("")
    lines.append(
        "Reliability is a verifiable admission decision over candidate mechanism evidence. It turns expert "
        "knowledge and LLM suggestions into falsifiable challengers of the anchor model, then admits only "
        "those challengers whose validation benefit, low-tail non-degradation, counterfactual sensitivity, "
        "and source/complexity profile justify deployment."
    )
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="Render the paper-ready reliability theory model.")
    parser.add_argument("--output", required=True)
    args = parser.parse_args(argv)

    report = render_report(ReliabilityTheorySpec.current())
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(report, encoding="utf-8")
    print(report)


if __name__ == "__main__":
    main()
