from __future__ import annotations

import unittest

from summarize_final_aaai_paper_package import render_package


class SummarizeFinalAaaiPaperPackageTest(unittest.TestCase):
    def test_render_package_contains_paper_level_claims_tables_and_boundaries(self) -> None:
        report = render_package()

        self.assertIn("# Final AAAI Paper Package", report)
        self.assertIn("Reliability-Calibrated Mechanism Evidence Fusion", report)
        self.assertIn("non-interventional industrial time series", report)
        self.assertIn("candidate mechanism evidence", report)
        self.assertIn("not a recovered true causal graph", report)

        self.assertIn("## Paper Contributions", report)
        self.assertIn("Evidence Reliability Estimator", report)
        self.assertIn("Hierarchical edge admission", report)
        self.assertIn("LLM as expert-graph conditional verifier", report)

        self.assertIn("## Main Result Table", report)
        self.assertIn("TEP", report)
        self.assertIn("0.9549 +/- 0.0023", report)
        self.assertIn("SKAB", report)
        self.assertIn("0.8209 +/- 0.0220", report)
        self.assertIn("Hydraulic", report)
        self.assertIn("C-MAPSS", report)

        self.assertIn("## Final Reliability Ablation Table", report)
        self.assertIn("CP recall about 0.9060", report)
        self.assertIn("0.8261 +/- 0.0138", report)
        self.assertIn("Full LLM-condition matrix", report)
        self.assertIn("algorithmic-only 0.8450 +/- 0.0189", report)
        self.assertIn("LLM condition gate 0.7981 +/- 0.0391", report)
        self.assertIn("not deployed", report)
        self.assertIn("GRU w80 cap125 RMSE 20.7559", report)
        self.assertIn("GRU w160 cap150 RMSE 18.0617", report)
        self.assertIn("AnchorPath cap150 w80 RMSE 18.6666 is not admitted", report)
        self.assertIn("aaai_edge_admission_protocol_audit", report)
        self.assertIn("protocol_and_evidence_complete", report)
        self.assertIn("three-seed/full-row TEP hierarchical edge probe", report)
        self.assertIn("admits no single edge", report)
        self.assertIn("SKAB LLM matrix rejects independent LLM edges", report)

        self.assertIn("## Matched Backbone Negative Controls", report)
        self.assertIn("PatchTST official-source adapted wrapper", report)
        self.assertIn("Graph WaveNet official-source adapted wrapper", report)
        self.assertIn("Anomaly Transformer official-source adapted wrapper", report)
        self.assertIn("0.4197 +/- 0.0320", report)
        self.assertIn("0.2854 +/- 0.0529", report)
        self.assertIn("0.4716 +/- 0.0487", report)
        self.assertIn("FAR 38.34", report)
        self.assertIn("MAR 63.29", report)
        self.assertIn("official_external_score=false", report)

        self.assertIn("## Exact-Native Protocol Gate", report)
        self.assertIn("official_sota_not_admissible", report)
        self.assertIn("aaai_sota_gap_ledger", report)
        self.assertIn("skab_official_baseline_gate", report)
        self.assertIn("skab_official_repository_baseline_audit", report)
        self.assertIn("recomputes the README outlier leaderboard rows", report)
        self.assertIn("Conv-AE (`F1 0.7838`, `FAR 13.55`, `MAR 28.02`)", report)
        self.assertIn("skab_official_source_rerun_audit", report)
        self.assertIn("T2 F1 0.6598", report)
        self.assertIn("T2+Q F1 0.7581", report)
        self.assertIn("MSET F1 0.7800", report)
        self.assertIn("Vanilla-AE F1 0.3938", report)
        self.assertIn("Conv-AE F1 0.7842", report)
        self.assertIn("LSTM-AE (`F1 0.7515`)", report)
        self.assertIn("MSCRED (`F1 0.3382`)", report)
        self.assertIn("Vanilla-LSTM (`F1 0.5111`)", report)
        self.assertIn("diagnostic rather than gate-closing evidence", report)
        self.assertIn("ArimaFD is not fully rerun or formally scoped out", report)
        self.assertIn("skab_source_rerun_delta_audit", report)
        self.assertIn("prediction-level rerun variance rather than row alignment or label errors", report)
        self.assertIn("current numeric gap ledger", report)
        self.assertIn("native split, preprocessing, metric", report)
        self.assertIn("exact-native execution plan", report)
        self.assertIn("SKAB is the first anomaly-detection target", report)
        self.assertIn("C-MAPSS is the first prognostics target", report)
        self.assertIn("skab_native_metric_audit", report)
        self.assertIn("cmapss_native_preprocessing_manifest", report)
        self.assertIn("cmapss_published_baseline_alignment", report)
        self.assertIn("cmapss_published_baseline_contract", report)
        self.assertIn("cmapss_lstm_source_protocol_audit", report)
        self.assertIn("cmapss_open_protocol_candidate_audit", report)
        self.assertIn("cmapss_mdfa_source_profile", report)
        self.assertIn("cmapss_mdfa_runner_audit", report)
        self.assertIn("cmapss_rul_backbone_optimization_audit", report)
        self.assertIn("cmapss_pseudo_truncation_validation_audit", report)
        self.assertIn("cmapss_exact_native_gap_audit", report)
        self.assertIn("pseudo_truncation_validation_complete_with_score_tradeoff", report)
        self.assertIn("frozen per-window prediction records", report)
        self.assertIn("FD001-FD004 terminal RUL records", report)
        self.assertIn("native preprocessing gate is now a pass", report)
        self.assertIn("three-seed LSTM published-style candidate", report)
        self.assertIn("RMSE 21.6521", report)
        self.assertIn("field-level exact reproduction checklist", report)
        self.assertIn("window=80", report)
        self.assertIn("IEEE full-text protocol is not available", report)
        self.assertIn("MDFA 2025", report)
        self.assertIn("ACB 2021", report)
        self.assertIn("FD004 train=249/test=248", report)
        self.assertIn("RMSE 41.8246", report)
        self.assertIn("completed three-seed branch archives", report)
        self.assertIn("FD001 `RMSE 12.5498`", report)
        self.assertIn("FD002 `RMSE 15.8410`", report)
        self.assertIn("FD003 `RMSE 12.9260`", report)
        self.assertIn("FD004 `RMSE 15.9596`", report)
        self.assertIn("source-style cap policy is not yet exact-native", report)
        self.assertIn("reduces the previous FD003 weakness", report)
        self.assertIn("cmapss_mdfa_strategy_probe_audit", report)
        self.assertIn("validation-only affine output-calibration, checkpoint snapshot-ensemble, and level+first-difference temporal-channel probes", report)
        self.assertIn("output calibration and checkpoint averaging remain blocked by the validation RMSE gain guard", report)
        self.assertIn("checkpoint snapshot-ensemble, and level+first-difference temporal-channel probes", report)
        self.assertIn("window80/all24_pca/dropout0.0 + level_diff", report)
        self.assertIn("level+first-difference temporal-channel probes", report)
        self.assertIn("window80/all24_pca/dropout0.1", report)
        self.assertIn("window80/all24_pca/dropout0.0", report)
        self.assertIn("707 terminal per-engine predictions", report)
        self.assertIn("exact-source RUL-label policy", report)
        self.assertIn("source-matched runner", report)
        self.assertIn("published reproduction, published-baseline preprocessing equivalence, matched budget", report)
        self.assertIn("native task/split/preprocessing/metric and seed archives pass", report)
        self.assertIn("MDFA local FD001-FD004 three-seed archive exists", report)
        self.assertIn("MDFA external source-resolution rows", report)
        self.assertIn("PCA threshold and source code/package remain unavailable", report)

        self.assertIn("## Efficiency Evidence", report)
        self.assertIn("SKAB | llm_condition_candidate_gate", report)
        self.assertIn("GDN20k no/residual", report)
        self.assertIn("MTADGAT20k no/residual", report)

        self.assertIn("## SOTA Claim Boundary", report)
        self.assertIn("Safe claim", report)
        self.assertIn("Unsafe claim", report)
        self.assertIn("universal official SOTA", report)
        self.assertIn("exact external leaderboard reproduction", report)

        self.assertIn("## Manuscript Assembly Checklist", report)
        self.assertIn("knowledge_exports/aaai_latex_draft/main.pdf", report)
        self.assertIn("knowledge_exports/manuscript_chinese_draft.md", report)
        self.assertIn("final_reliability_ablation_table.md", report)
        self.assertIn("hierarchical_edge_probe_admission.md", report)
        self.assertIn("tep_hierarchical_edge_validation_probe_3seed_fullrows.md", report)
        self.assertIn("aaai_edge_admission_protocol_audit.md", report)
        self.assertIn("llm_condition_verifier_ablation_matrix.md", report)
        self.assertIn("aaai_efficiency_audit.md", report)
        self.assertIn("aaai_seed_level_ablation_evidence.md", report)
        self.assertIn("aaai_ablation_coverage_audit.md", report)
        self.assertIn("aaai_external_baseline_alignment_decision.md", report)
        self.assertIn("aaai_pending_baseline_gate.md", report)
        self.assertIn("aaai_exact_native_protocol_gate.md", report)
        self.assertIn("aaai_exact_native_execution_plan.md", report)
        self.assertIn("aaai_sota_gap_ledger.md", report)
        self.assertIn("skab_official_baseline_gate.md", report)
        self.assertIn("skab_official_repository_baseline_audit.md", report)
        self.assertIn("skab_official_source_rerun_audit.md", report)
        self.assertIn("diagnostic LSTM-AE/MSCRED/Vanilla-LSTM reruns", report)
        self.assertIn("skab_native_metric_audit.md", report)
        self.assertIn("cmapss_native_preprocessing_manifest.md", report)
        self.assertIn("cmapss_published_baseline_alignment.md", report)
        self.assertIn("cmapss_published_baseline_contract.md", report)
        self.assertIn("cmapss_lstm_source_protocol_audit.md", report)
        self.assertIn("cmapss_open_protocol_candidate_audit.md", report)
        self.assertIn("cmapss_mdfa_source_profile.md", report)
        self.assertIn("cmapss_mdfa_runner_audit.md", report)
        self.assertIn("cmapss_mdfa_strategy_probe_audit.md", report)
        self.assertIn("cmapss_mdfa_source_matched_smoke_summary.md", report)
        self.assertIn("cmapss_pseudo_truncation_validation_audit.md", report)
        self.assertIn("cmapss_exact_native_gap_audit.md", report)
        self.assertIn("MDFA external source-resolution evidence", report)
        self.assertIn("run_public_ms_gse_rpf_experiment.py", report)
        self.assertIn("classification prediction records", report)
        self.assertIn("run_cmapss_rul_baselines.py", report)
        self.assertIn("GRU, LSTM, and TCN terminal RUL baseline runner", report)
        self.assertIn("run_cmapss_mdfa_source_matched.py", report)
        self.assertIn("skab_external_baselines.py", report)
        self.assertIn("skab_official_baseline_gate.py", report)
        self.assertIn("skab_official_repository_baseline_audit.py", report)
        self.assertIn("skab_official_source_rerun_audit.py", report)
        self.assertIn("remaining ArimaFD/source protocol blockers", report)
        self.assertIn("skab_source_rerun_delta_audit.py", report)
        self.assertIn("USAD/TranAD-style", report)
        self.assertIn("cmapss_published_baseline_alignment.py", report)
        self.assertIn("cmapss_published_baseline_contract.py", report)
        self.assertIn("cmapss_lstm_source_protocol_audit.py", report)
        self.assertIn("cmapss_open_protocol_candidate_audit.py", report)
        self.assertIn("cmapss_mdfa_source_profile.py", report)
        self.assertIn("cmapss_mdfa_runner_audit.py", report)
        self.assertIn("cmapss_mdfa_strategy_probe_audit.py", report)
        self.assertIn("cmapss_pseudo_truncation_validation_audit.py", report)
        self.assertIn("cmapss_exact_native_gap_audit.py", report)
        self.assertIn("MDFA source-resolution audit", report)
        self.assertIn("aaai_edge_admission_protocol_audit.py", report)
        self.assertIn("llm_condition_verifier_ablation_matrix.py", report)
        self.assertIn("run_patchtst_tep_official_wrapper.py", report)
        self.assertIn("run_graph_wavenet_tep_official_wrapper.py", report)
        self.assertIn("run_anomaly_transformer_skab_official_wrapper.py", report)
        self.assertIn("reference_verification_report.md", report)
        self.assertIn("references.bib", report)
        self.assertIn("Chinese reading draft is now regenerated as valid UTF-8 text", report)
        self.assertIn("English draft compiles cleanly", report)
        self.assertIn("remaining blocker for the original long-term goal", report)


if __name__ == "__main__":
    unittest.main()
